package com.othsoft.model;
// Generated Jul 8, 2018 2:04:35 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CartLine generated by hbm2java
 */
@Entity
@Table(name = "cart_line", catalog = "shoppingCart")
public class CartLine implements java.io.Serializable {

	private Long id;
	private Long cartId;
	private BigDecimal total;
	private Long productId;
	private Integer productCount;
	private BigDecimal buyingPrice;
	private Boolean isAvailable;

	public CartLine() {
	}

	public CartLine(Long cartId, BigDecimal total, Long productId, Integer productCount, BigDecimal buyingPrice,
			Boolean isAvailable) {
		this.cartId = cartId;
		this.total = total;
		this.productId = productId;
		this.productCount = productCount;
		this.buyingPrice = buyingPrice;
		this.isAvailable = isAvailable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "cart_id")
	public Long getCartId() {
		return this.cartId;
	}

	public void setCartId(Long cartId) {
		this.cartId = cartId;
	}

	@Column(name = "total", precision = 10)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "product_id")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "product_count")
	public Integer getProductCount() {
		return this.productCount;
	}

	public void setProductCount(Integer productCount) {
		this.productCount = productCount;
	}

	@Column(name = "buying_price", precision = 10)
	public BigDecimal getBuyingPrice() {
		return this.buyingPrice;
	}

	public void setBuyingPrice(BigDecimal buyingPrice) {
		this.buyingPrice = buyingPrice;
	}

	@Column(name = "is_available")
	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

}
