package com.othsoft.model;
// Generated Jul 8, 2018 2:04:35 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", schema = "shoppingCart")
public class Cart implements java.io.Serializable {

	private Long id;
	private Long userId;
	private BigDecimal grandTotal;
	private Integer cartLines;

	public Cart() {
	}

	public Cart(Long userId, BigDecimal grandTotal, Integer cartLines) {
		this.userId = userId;
		this.grandTotal = grandTotal;
		this.cartLines = cartLines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "grand_total", precision = 10)
	public BigDecimal getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(BigDecimal grandTotal) {
		this.grandTotal = grandTotal;
	}

	@Column(name = "cart_lines")
	public Integer getCartLines() {
		return this.cartLines;
	}

	public void setCartLines(Integer cartLines) {
		this.cartLines = cartLines;
	}

}
