package com.othsoft.model;
// Generated Jul 8, 2018 2:04:35 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "order_item", schema = "shoppingCart")
public class OrderItem implements java.io.Serializable {

	private Long id;
	private Long orderId;
	private BigDecimal total;
	private Long productId;
	private Integer productCount;
	private BigDecimal buyingPrice;

	public OrderItem() {
	}

	public OrderItem(Long orderId, BigDecimal total, Long productId, Integer productCount, BigDecimal buyingPrice) {
		this.orderId = orderId;
		this.total = total;
		this.productId = productId;
		this.productCount = productCount;
		this.buyingPrice = buyingPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "total", precision = 10)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "product_id")
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "product_count")
	public Integer getProductCount() {
		return this.productCount;
	}

	public void setProductCount(Integer productCount) {
		this.productCount = productCount;
	}

	@Column(name = "buying_price", precision = 10)
	public BigDecimal getBuyingPrice() {
		return this.buyingPrice;
	}

	public void setBuyingPrice(BigDecimal buyingPrice) {
		this.buyingPrice = buyingPrice;
	}

}
