package com.othsoft.model;
// Generated Jul 8, 2018 2:04:35 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail", schema = "shoppingCart")
public class OrderDetail implements java.io.Serializable {

	private Long id;
	private Long userId;
	private BigDecimal orderTotal;
	private Integer orderCount;
	private Long shippingId;
	private Long billingId;
	private Date orderDate;

	public OrderDetail() {
	}

	public OrderDetail(Long userId, BigDecimal orderTotal, Integer orderCount, Long shippingId, Long billingId,
			Date orderDate) {
		this.userId = userId;
		this.orderTotal = orderTotal;
		this.orderCount = orderCount;
		this.shippingId = shippingId;
		this.billingId = billingId;
		this.orderDate = orderDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "order_total", precision = 10)
	public BigDecimal getOrderTotal() {
		return this.orderTotal;
	}

	public void setOrderTotal(BigDecimal orderTotal) {
		this.orderTotal = orderTotal;
	}

	@Column(name = "order_count")
	public Integer getOrderCount() {
		return this.orderCount;
	}

	public void setOrderCount(Integer orderCount) {
		this.orderCount = orderCount;
	}

	@Column(name = "shipping_id")
	public Long getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(Long shippingId) {
		this.shippingId = shippingId;
	}

	@Column(name = "billing_id")
	public Long getBillingId() {
		return this.billingId;
	}

	public void setBillingId(Long billingId) {
		this.billingId = billingId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", length = 10)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
